apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-dog.fullname" . }}
  labels:
    {{- include "demo-dog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ingest
      port: {{ .Values.service.ingestPort }}
      targetPort: ingest
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "demo-dog.selectorLabels" . | nindent 4 }}
