{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dog-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dog-collector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dog-collector.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
