apiVersion: v1
kind: Service
metadata:
  name: {{ include "dog-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dog-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: http
  selector:
    {{- include "dog-collector.selectorLabels" . | nindent 4 }}
